#%RAML 1.0 Library
types:
  update_task:  
    description: updating an task
    type: object
    properties:
      id:
         description: id 
         type: string
         required: true
  update_task_response:
    type: object
    properties:
      is_success:
        type: boolean
      salesforce_id:
        type: string
      errors:
        type: array    
  